/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import project.DBConnection;
import project.Select;

/**
 *
 * @author neths
 */
public class CusInfo extends javax.swing.JFrame {

    /**
     * Creates new form CusInfo
     */
    public CusInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CusInfoTable = new javax.swing.JTable();
        UpdateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        homebutton = new javax.swing.JButton();
        CusID = new javax.swing.JTextField();
        CusName = new javax.swing.JTextField();
        CusAddress = new javax.swing.JTextField();
        CusMobile = new javax.swing.JTextField();
        CusAge = new javax.swing.JTextField();
        CusEmail = new javax.swing.JTextField();
        CusGender = new javax.swing.JTextField();
        CusNIC = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Customer Info");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 15, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel2.setText("Customer ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 78, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 112, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel4.setText("Address");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 152, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel5.setText("Mobile");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 184, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel6.setText("NIC");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 184, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel7.setText("Email");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 112, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel8.setText("Gender");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 152, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel9.setText("Age");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 78, -1, -1));

        CusInfoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Address", "Mobile", "Age", "Email", "Gender", "NIC"
            }
        ));
        CusInfoTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CusInfoTableMouseClicked(evt);
            }
        });
        CusInfoTable.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                CusInfoTableComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(CusInfoTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 246, 658, 252));

        UpdateButton.setBackground(new java.awt.Color(0, 0, 102));
        UpdateButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        UpdateButton.setForeground(new java.awt.Color(255, 255, 255));
        UpdateButton.setText("UPDATE");
        UpdateButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 516, 77, -1));

        deleteButton.setBackground(new java.awt.Color(0, 0, 102));
        deleteButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setText("DELETE");
        deleteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 516, 77, -1));

        homebutton.setBackground(new java.awt.Color(0, 0, 102));
        homebutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        homebutton.setForeground(new java.awt.Color(255, 255, 255));
        homebutton.setText("HOME");
        homebutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(homebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 516, 75, -1));
        getContentPane().add(CusID, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 75, 200, -1));
        getContentPane().add(CusName, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 109, 200, -1));

        CusAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CusAddressActionPerformed(evt);
            }
        });
        getContentPane().add(CusAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 149, 200, -1));
        getContentPane().add(CusMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 181, 200, -1));

        CusAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CusAgeActionPerformed(evt);
            }
        });
        getContentPane().add(CusAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 75, 200, -1));

        CusEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CusEmailActionPerformed(evt);
            }
        });
        getContentPane().add(CusEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 109, 200, -1));

        CusGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CusGenderActionPerformed(evt);
            }
        });
        getContentPane().add(CusGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 149, 200, -1));

        CusNIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CusNICActionPerformed(evt);
            }
        });
        getContentPane().add(CusNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 181, 200, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/all pages background.png"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CusAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CusAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CusAddressActionPerformed

    private void CusAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CusAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CusAgeActionPerformed

    private void CusEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CusEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CusEmailActionPerformed

    private void CusNICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CusNICActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CusNICActionPerformed

    private void CusGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CusGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CusGenderActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(CusInfoTable.getValueAt(CusInfoTable.getSelectedRow(), 0).toString());
        try {
            Connection con = DBConnection.getconConnection();
            Statement st = con.createStatement();
            boolean b = st.execute("UPDATE customer SET Cus_Name='" + CusName.getText() + "',Cus_Address='" + CusAddress.getText() + "',Mobile='" + CusMobile.getText()+ "',Age='" + CusAge.getText() + "',Email='" + CusEmail.getText() + "',Gender='" + CusGender.getText() + "',NIC='" + CusNIC.getText() + "' Where CusID =" + id);
            if (!b) {
                setVisible(false);
                new CusInfo().setVisible(true);
            }
        } catch (Exception e) {
           JOptionPane.showMessageDialog(this, "Error");
        }
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(CusInfoTable.getValueAt(CusInfoTable.getSelectedRow(), 0).toString());
        try {
            Connection con = DBConnection.getconConnection();
            Statement st = con.createStatement();
            int r = JOptionPane.showConfirmDialog(this, "Are u sure delete selected row?");
            if (r == 0) {
                st.execute("DELETE FROM customer WHERE cusid=" + id);
                setVisible(false);
                new CusInfo().setVisible(true);
            }
        } catch (Exception e) {
            e.printStackTrace();

        }

    }//GEN-LAST:event_deleteButtonActionPerformed

    private void CusInfoTableComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_CusInfoTableComponentShown
       
    }//GEN-LAST:event_CusInfoTableComponentShown

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
         ResultSet resultSet = Select.getData("SELECT * FROM customer");
        DefaultTableModel model = (DefaultTableModel) CusInfoTable.getModel();
        try {
            while (resultSet.next()) {
                model.addRow(new Object[]{resultSet.getString(1), resultSet.getString(2), resultSet.getString(3), resultSet.getString(4), resultSet.getString(5), resultSet.getString(6), resultSet.getString(7), resultSet.getString(8)});
            }
            resultSet.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formComponentShown

    private void CusInfoTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CusInfoTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tbleModel = (DefaultTableModel) CusInfoTable.getModel();

        String ID = tbleModel.getValueAt(CusInfoTable.getSelectedRow(), 0).toString();
        String Name = tbleModel.getValueAt(CusInfoTable.getSelectedRow(), 1).toString();
        String Address = tbleModel.getValueAt(CusInfoTable.getSelectedRow(), 2).toString();
        String Mobile = tbleModel.getValueAt(CusInfoTable.getSelectedRow(), 3).toString();
        String Age = tbleModel.getValueAt(CusInfoTable.getSelectedRow(), 4).toString();
        String Email = tbleModel.getValueAt(CusInfoTable.getSelectedRow(), 5).toString();
        String Gender = tbleModel.getValueAt(CusInfoTable.getSelectedRow(), 6).toString();
        String NIC = tbleModel.getValueAt(CusInfoTable.getSelectedRow(), 7).toString();

        CusID.setText(ID);
        CusName.setText(Name);
        CusAddress.setText(Address);
        CusMobile.setText(Mobile);
        CusAge.setText(Age);
        CusEmail.setText(Email);
        CusGender.setText(Gender);
        CusNIC.setText(NIC);
    }//GEN-LAST:event_CusInfoTableMouseClicked

    private void homebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebuttonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new home().setVisible(true);
    }//GEN-LAST:event_homebuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CusInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CusInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CusInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CusInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CusInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CusAddress;
    private javax.swing.JTextField CusAge;
    private javax.swing.JTextField CusEmail;
    private javax.swing.JTextField CusGender;
    private javax.swing.JTextField CusID;
    private javax.swing.JTable CusInfoTable;
    private javax.swing.JTextField CusMobile;
    private javax.swing.JTextField CusNIC;
    private javax.swing.JTextField CusName;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton homebutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
