/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import project.*;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author neths
 */
public class Customer extends javax.swing.JFrame {


    /**
     * Creates new form Customer
     */
    public Customer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CusGender = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        CusAge = new javax.swing.JTextField();
        CusAddress = new javax.swing.JTextField();
        home = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        CusName = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CusEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        CusLable = new javax.swing.JLabel();
        CusMobile = new javax.swing.JTextField();
        NIC = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CusGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        CusGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CusGenderActionPerformed(evt);
            }
        });
        getContentPane().add(CusGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 285, 136, -1));

        jLabel7.setFont(new java.awt.Font("Eras Bold ITC", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("Email");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 248, -1, -1));
        getContentPane().add(CusAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 211, 77, -1));
        getContentPane().add(CusAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 137, 300, -1));

        home.setBackground(new java.awt.Color(0, 0, 0));
        home.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setText("HOME");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 364, 83, -1));

        jLabel8.setFont(new java.awt.Font("Eras Bold ITC", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("Gender");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 285, -1, -1));

        CusName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CusNameActionPerformed(evt);
            }
        });
        getContentPane().add(CusName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 300, -1));

        add.setBackground(new java.awt.Color(0, 0, 0));
        add.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 364, 83, -1));

        jLabel4.setFont(new java.awt.Font("Eras Bold ITC", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Address");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 138, -1, -1));

        jLabel3.setFont(new java.awt.Font("Eras Bold ITC", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));
        getContentPane().add(CusEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 248, 300, -1));

        jLabel5.setFont(new java.awt.Font("Eras Bold ITC", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Mobile");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 174, -1, -1));

        jLabel6.setFont(new java.awt.Font("Eras Bold ITC", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("Age");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 212, -1, -1));

        jLabel9.setFont(new java.awt.Font("Eras Bold ITC", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 102));
        jLabel9.setText("NIC");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 322, -1, -1));

        CusLable.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        CusLable.setForeground(new java.awt.Color(0, 0, 153));
        CusLable.setText("CUSTOMER");
        getContentPane().add(CusLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));
        getContentPane().add(CusMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 174, 300, -1));
        getContentPane().add(NIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 322, 302, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/all pages background.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CusNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CusNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CusNameActionPerformed

    private void CusGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CusGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CusGenderActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new home().setVisible(true);
    }//GEN-LAST:event_homeActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        String name=CusName.getText();
        String email= CusEmail.getText();
        String address= CusAddress.getText();
        String mobile=CusMobile.getText();
        String age = CusAge.getText();
        String gender= (String)CusGender.getSelectedItem();
        String nic= NIC.getText();
        if(name.equals("")|| email.equals("")||address.equals("")|| mobile.equals("")|| gender.equals("")||nic.equals(""))
            JOptionPane.showMessageDialog(null, "Every Field is Required");
        else{
            String Query;
            Query = "INSERT INTO Customer(Cus_name,Cus_address,Mobile,age,Email,Gender,Nic) VALUES('"+name+"','"+address+"','"+mobile+"','"+age+"','"+email+"','"+gender+"','"+nic+"')";
            InsertUpdateDelete.setData(Query, "Registered Successfully");
            setVisible(false);
            new Customer().setVisible(true);
        }
    }//GEN-LAST:event_addActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CusAddress;
    private javax.swing.JTextField CusAge;
    private javax.swing.JTextField CusEmail;
    private javax.swing.JComboBox<String> CusGender;
    private javax.swing.JLabel CusLable;
    private javax.swing.JTextField CusMobile;
    private javax.swing.JTextField CusName;
    private javax.swing.JTextField NIC;
    private javax.swing.JButton add;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
