/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;
import project.*;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author neths
 */
public class Room extends javax.swing.JFrame {

    /**
     * Creates new form Room
     */
    public Room() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topic = new javax.swing.JLabel();
        Rnumber = new javax.swing.JLabel();
        Rtype = new javax.swing.JLabel();
        Btype = new javax.swing.JLabel();
        Lprice = new javax.swing.JLabel();
        roomnumber = new javax.swing.JTextField();
        roomtype = new javax.swing.JComboBox<>();
        bedtype = new javax.swing.JComboBox<>();
        roomPrice = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        RoomTable = new javax.swing.JTable();
        homeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topic.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        topic.setForeground(new java.awt.Color(0, 0, 204));
        topic.setText("ADD ROOMS");
        getContentPane().add(topic, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        Rnumber.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        Rnumber.setForeground(new java.awt.Color(0, 0, 102));
        Rnumber.setText("Room Number");
        getContentPane().add(Rnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        Rtype.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        Rtype.setForeground(new java.awt.Color(0, 0, 102));
        Rtype.setText("Room Type");
        getContentPane().add(Rtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        Btype.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        Btype.setForeground(new java.awt.Color(0, 0, 102));
        Btype.setText("Bed Type");
        getContentPane().add(Btype, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        Lprice.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        Lprice.setForeground(new java.awt.Color(0, 0, 102));
        Lprice.setText("Price");
        getContentPane().add(Lprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        roomnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomnumberActionPerformed(evt);
            }
        });
        getContentPane().add(roomnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 131, -1));

        roomtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A/C", "Non A/C" }));
        getContentPane().add(roomtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 131, -1));

        bedtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single ", "Double ", "Triple" }));
        getContentPane().add(bedtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 131, -1));
        getContentPane().add(roomPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 131, -1));

        addButton.setBackground(new java.awt.Color(0, 0, 51));
        addButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 12)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 80, -1));

        RoomTable.setBackground(new java.awt.Color(255, 255, 255));
        RoomTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Number", "Type", "Bed Type", "Price"
            }
        ));
        RoomTable.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(RoomTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 40, 418, 397));

        homeButton.setBackground(new java.awt.Color(0, 0, 51));
        homeButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 12)); // NOI18N
        homeButton.setForeground(new java.awt.Color(255, 255, 255));
        homeButton.setText("HOME");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 80, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/all pages background.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void roomnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomnumberActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        String roomNo = roomnumber.getText();
        String roomType = (String)roomtype.getSelectedItem();
        String bedType = (String)bedtype.getSelectedItem();
        String price = roomPrice.getText();
        
        String Query = "INSERT INTO rooms VALUES('"+roomNo+"','"+roomType+"','"+bedType+"','"+price+"','Available')";
        
        InsertUpdateDelete.setData(Query, "Successfully Updated");
        setVisible(false);
        new Room().setVisible(true);
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new home().setVisible(true);
    }//GEN-LAST:event_homeButtonActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        ResultSet resultSet = Select.getData("SELECT * FROM rooms");
        DefaultTableModel model = (DefaultTableModel)RoomTable.getModel();
        try {
            while(resultSet.next()){
                model.addRow(new Object[]{resultSet.getString(1),resultSet.getString(2),resultSet.getString(3),resultSet.getString(4),resultSet.getString(5)});
            }
            resultSet.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Room().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Btype;
    private javax.swing.JLabel Lprice;
    private javax.swing.JLabel Rnumber;
    private javax.swing.JTable RoomTable;
    private javax.swing.JLabel Rtype;
    private javax.swing.JButton addButton;
    private javax.swing.JComboBox<String> bedtype;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField roomPrice;
    private javax.swing.JTextField roomnumber;
    private javax.swing.JComboBox<String> roomtype;
    private javax.swing.JLabel topic;
    // End of variables declaration//GEN-END:variables
}
